version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-observability}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  openobserve:
    image: openobserve/openobserve:latest
    environment:
      ZO_ROOT_USER_EMAIL: ${OPENOBSERVE_EMAIL:-root@example.com}
      ZO_ROOT_USER_PASSWORD: ${OPENOBSERVE_PASSWORD:-changeme}
    ports:
      - "5080:5080"
    volumes:
      - oo-data:/data
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config", "/etc/otelcol.yaml"]
    volumes:
      - ./configs/otelcol.yaml:/etc/otelcol.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - openobserve
volumes:
  db-data:
  oo-data:
