receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp/openobserve:
    endpoint: http://openobserve:5080/api/default/default/
    compression: gzip
    headers:
      # Basic auth header; replace with base64 encoded email:password if needed
      Authorization: "Basic ${OPENOBSERVE_BASIC_AUTH}"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [otlphttp/openobserve]
    logs:
      receivers: [otlp]
      exporters: [otlphttp/openobserve]
    traces:
      receivers: [otlp]
      exporters: [otlphttp/openobserve]
